FROM apache/airflow:2.9.2

USER root

# Fix permissions & install system packages
RUN apt-get update && apt-get install -y git && apt-get clean && rm -rf /var/lib/apt/lists/*

USER airflow

RUN pip install --no-cache-dir \
    mlflow==2.9.2 \
    google-cloud-storage

