apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: gcr.io/poojaproject/flask-app:latest  # Your Docker image
        ports:
        - containerPort: 5000  # Your Flask app port
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: "/secrets/key.json"  # How your app reads GCP credentials
        volumeMounts:
        - name: gcp-key
          mountPath: /secrets
          readOnly: true
      volumes:
      - name: gcp-key
        secret:
          secretName: gcp-credentials
