tables:
  bundle_data:
    columns:
      bundle_final_price : VARCHAR
      bundle_url : VARCHAR
      bundle_price : VARCHAR
      bundle_name : VARCHAR
      bundle_id : VARCHAR
      items : VARCHAR
      bundle_discount : VARCHAR
  item_data:
    columns:
      publisher : VARCHAR
      genres : VARCHAR
      app_name : VARCHAR
      title : VARCHAR
      url : VARCHAR
      release_date : VARCHAR
      tags : VARCHAR
      discount_price : VARCHAR
      reviews_url : VARCHAR
      specs : VARCHAR
      price : VARCHAR
      early_access : VARCHAR
      id : VARCHAR
      developer : VARCHAR
      sentiment : VARCHAR
      metascore : VARCHAR
  reviews_data:
    columns:
      compensation : VARCHAR
      date : DATE
      early_access : VARCHAR
      found_funny : VARCHAR
      hours : VARCHAR
      page : VARCHAR
      page_order : VARCHAR
      product_id : VARCHAR
      products : VARCHAR
      text : VARCHAR
      user_id : VARCHAR
      username : VARCHAR