name: Data Preprocessing Tests

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.ref }}
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Remove 'os' from requirements.txt
      run: sed -i '/^os$/d' requirements.txt
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt 
    - name: Add project root to PYTHONPATH
      run: echo "PYTHONPATH=$PYTHONPATH:${{ github.workspace }}" >> $GITHUB_ENV
    - name: Run unittests
      run: python -m unittest discover -v
    - name: Notify on success
      if: success()
      run: echo "Unit tests passed successfully"
    - name: Notify on failure
      if: failure()
      run: echo "Unit tests failed"
