name: GCP Kubernetes Deployment

on:
  push:
    branches:
      - deploy-automation  # change this if your branch is different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # ✅ Step 1: Authenticate with GCP using the secret
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.gcp_key }}  # match the secret your friend added

    # ✅ Step 2: Set up the gcloud CLI
    - name: Set up gcloud CLI
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: poojaproject

    - name: Authenticate Docker to GCR
      run: gcloud auth configure-docker

    - name: Build Docker images
      run: |
        docker build -t gcr.io/poojaproject/flask-app -f Dockerfile.flask .
        docker build -t gcr.io/poojaproject/airflow -f Dockerfile.airflow .
        docker build -t gcr.io/poojaproject/mlflow -f Dockerfile.mlflow .

    - name: Push Docker images to GCR
      run: |
        docker push gcr.io/poojaproject/flask-app
        docker push gcr.io/poojaproject/airflow
        docker push gcr.io/poojaproject/mlflow

    - name: Get GKE credentials
      run: gcloud container clusters get-credentials steam-select-clusters --region=us-east1

    - name: Create K8s secret and deploy
      run: |
        kubectl create secret generic gcp-credentials --from-literal=key.json="${{ secrets.gcp_key }}" --dry-run=client -o yaml | kubectl apply -f -
        kubectl apply -f kubernetes/
