name: GCP Kubernetes Deployment

on:
  push:
    branches:
      - deploy-automation  # or your working branch

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 1: Authenticate with GCP
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.gcp_key }}

    # Step 2: Set up gcloud CLI
    - name: Set up gcloud CLI
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: poojaproject

    # Step 3: Build and Save Docker Images
    - name: Build and Save Docker Image
      run: |
        docker build -t flask-app -f Dockerfile.flask .
        docker save flask-app | gzip > flask-app.tar.gz

    # Step 4: Upload Docker Image to GCS
    - name: Upload to GCS
      run: |
        gsutil cp flask-app.tar.gz gs://steam-select/docker-images/

    # Step 5: Get GKE credentials (optional if deploying K8s objects)
    - name: Get GKE credentials
      run: gcloud container clusters get-credentials steam-select-clusters --region=us-east1

    #FIX: Install GKE auth plugin
    - name: Install gke-gcloud-auth-plugin
      run: |
        sudo apt-get update && sudo apt-get install -y google-cloud-sdk-gke-gcloud-auth-plugin

    # Step 6: Apply Kubernetes config and secret
    - name: Write GCP key to file and create Kubernetes secret
      run: |
        echo "${{ secrets.gcp_key }}" > gcp-key.json
        kubectl create secret generic gcp-credentials --from-file=key.json=gcp-key.json --dry-run=client -o yaml | kubectl apply -f -
