name: GCP Kubernetes Deployment

on:
  push:
    branches:
      - main  # or change to your default branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: poojaproject
        service_account_key: ${{ secrets.gcp_key }}
        export_default_credentials: true

    - name: Authenticate Docker with GCR
      run: gcloud auth configure-docker

    - name: Build Docker images
      run: |
        docker build -t gcr.io/poojaproject/flask-app -f Dockerfile.flask .
        docker build -t gcr.io/poojaproject/airflow -f Dockerfile.airflow .
        docker build -t gcr.io/poojaproject/mlflow -f Dockerfile.mlflow .

    - name: Push Docker images to GCR
      run: |
        docker push gcr.io/poojaproject/flask-app
        docker push gcr.io/poojaproject/airflow
        docker push gcr.io/poojaproject/mlflow

    - name: Get GKE credentials
      run: gcloud container clusters get-credentials steam-select-clusters --region=us-east1

    - name: Create Kubernetes secret and deploy
      run: |
        kubectl create secret generic gcp-credentials --from-literal=key.json="${{ secrets.gcp_key }}" --dry-run=client -o yaml | kubectl apply -f -
        kubectl apply -f kubernetes/
