name: GCP Kubernetes Deployment

on:
  push:
    branches:
      - deploy-automation  # or your working branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 1: Authenticate with GCP
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.gcp_key }}

    # Step 2: Set up gcloud CLI
    - name: Set up gcloud CLI
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: poojaproject

    # Step 3: Build and Save Docker Image
    - name: Build and Save Docker Image
      run: |
        docker build -t flask-app -f Dockerfile.flask .
        docker save flask-app | gzip > flask-app.tar.gz

    # Step 4: Upload Docker Image to GCS
    - name: Upload to GCS
      run: |
        gsutil cp flask-app.tar.gz gs://steam-select-artifacts/docker-images/  # ✅ Update with actual bucket

    # Step 5: Get GKE credentials (optional if deploying K8s objects)
    - name: Get GKE credentials
      run: gcloud container clusters get-credentials steam-select-clusters --region=us-east1

    # Step 6: Apply Kubernetes config and secret
    - name: Create K8s secret and deploy
      run: |
        kubectl create secret generic gcp-credentials --from-literal=key.json="${{ secrets.gcp_key }}" --dry-run=client -o yaml | kubectl apply -f -
        kubectl apply -f kubernetes/
